export const actionType = {
  SET_ME: "SET_ME",
  SET_USERS: "SET_USERS",
  SET_USER_DETAIL: "SET_USER_DETAIL",
  SET_MOVIES: "SET_MOVIES",
  SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
  SET_SHOWTIMES: "SET_SHOWTIMES",
};
